// <auto-generated />
using System;
using FacetIQ.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacetIQ.Data.Migrations.App
{
    [DbContext(typeof(FacetIQDbContext))]
    partial class FacetIQDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacetIQ.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DenyReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("JustifyingPrinciple")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("NormId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NormVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestedAttributeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Transform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransformParameter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Timestamp");

                    b.ToTable("audit_records", "app");
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.Norm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DenyReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("JustifyingPrinciple")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Transform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransformParameter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id", "Version");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SubjectId", "SupersededAt");

                    b.ToTable("norms", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000020"),
                            Version = 1,
                            Action = "Return",
                            AttributeId = new Guid("0a5f4d8e-0000-4000-8000-000000000010"),
                            JustifyingPrinciple = "GDPR Art. 6(1)(c): disclosure necessary for a legal obligation.",
                            Purpose = "Regulatory",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Transform = "None"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000021"),
                            Version = 1,
                            Action = "Return",
                            AttributeId = new Guid("0a5f4d8e-0000-4000-8000-000000000011"),
                            JustifyingPrinciple = "Contextual integrity: the professional context expects the professional name.",
                            Purpose = "Clinical",
                            Relationship = "colleague",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Transform = "None"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000022"),
                            Version = 1,
                            Action = "Return",
                            AttributeId = new Guid("0a5f4d8e-0000-4000-8000-000000000012"),
                            JustifyingPrinciple = "Contextual integrity: a social enquiry warrants the name used socially.",
                            Purpose = "Social",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Transform = "None"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000023"),
                            Version = 1,
                            Action = "Transform",
                            AttributeId = new Guid("0a5f4d8e-0000-4000-8000-000000000013"),
                            JustifyingPrinciple = "GDPR Art. 5(1)(c): a threshold satisfies the purpose without the date.",
                            Purpose = "Social",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Transform = "Generalise",
                            TransformParameter = "18"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000024"),
                            Version = 1,
                            Action = "Return",
                            AttributeId = new Guid("0a5f4d8e-0000-4000-8000-000000000013"),
                            JustifyingPrinciple = "GDPR Art. 6(1)(c): identity verification requires the recorded date.",
                            Purpose = "Regulatory",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Transform = "None"
                        });
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("IssuerKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "RequesterUserId");

                    b.ToTable("standings", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000030"),
                            AcceptedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IssuedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Issuer = "Example Teaching Hospital",
                            IssuerKind = "Institution",
                            RequesterUserId = "seed-colleague-accepted",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "colleague"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000031"),
                            IssuedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Issuer = "seed-amara",
                            IssuerKind = "Subject",
                            RequesterUserId = "seed-colleague-pending",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "colleague"
                        });
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("subjects", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            UserId = "seed-amara"
                        });
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.SubjectAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectedFor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Key");

                    b.ToTable("subject_attributes", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000010"),
                            Key = "name",
                            Label = "legal",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "Amara Chidinma Nwosu"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000011"),
                            Key = "name",
                            Label = "professional",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "Dr Amara Nwosu"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000012"),
                            Key = "name",
                            Label = "social",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "Amara"
                        },
                        new
                        {
                            Id = new Guid("0a5f4d8e-0000-4000-8000-000000000013"),
                            CollectedFor = "Social",
                            Key = "dateOfBirth",
                            Label = "legal",
                            SubjectId = new Guid("0a5f4d8e-0000-4000-8000-000000000001"),
                            Value = "1994-03-11"
                        });
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.Norm", b =>
                {
                    b.HasOne("FacetIQ.Domain.Entities.SubjectAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.SubjectAttribute", b =>
                {
                    b.HasOne("FacetIQ.Domain.Entities.Subject", null)
                        .WithMany("Attributes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacetIQ.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
