name: Publish Main 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  WEBAPP_NAME: FacetIQ
  WEBAPP_PCKG_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: restore
        run: dotnet restore ./FacetIQ.slnx

      - name: Build
        run: dotnet build ./FacetIQ.slnx --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./FacetIQ.slnx --configuration Release --no-build --output '${{env.WEBAPP_PCKG_PATH}}'

      - name: Deploy API
        uses: actions/webapps-deploy@latest
        with:
          app-name: ${{env.WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: ${{env.WEBAPP_PCKG_PATH}}
